"""empty message

Revision ID: 220249d22da8
Revises: 2788795ed341
Create Date: 2026-09-28 20:24:04.543382

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '220249d22da8'
down_revision: str | Sequence[str] | None = '2788795ed341'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('large_object_key', sa.String(length=512), nullable=False),
    sa.Column('thumbnail_object_key', sa.String(length=512), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.CheckConstraint('position BETWEEN 0 and 7', name='ck_product_image_position_between_0_and_7'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'position', deferrable=True, initially='DEFERRED', name='uq_product_id_position')
    )
    op.add_column('products', sa.Column('model_3d_key', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'model_3d_key')
    op.drop_table('product_images')
    # ### end Alembic commands ###
