"""require positive products price

Revision ID: 2788795ed341
Revises: 65852ca7bb69
Create Date: 2026-09-20 16:25:53.111428

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa



revision: str = '2788795ed341'
down_revision: str | Sequence[str] | None = '65852ca7bb69'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_products_price_non_negative'), 'products', type_='check')
    op.create_check_constraint('ck_products_price_positive', 'products', 'price > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_products_price_positive', 'products', type_='check')
    op.create_check_constraint(op.f('ck_products_price_non_negative'), 'products', 'price >= 0::numeric')
    # ### end Alembic commands ###
