"""add stock reservations and messaging tables

Revision ID: 65852ca7bb69
Revises: 659229e85be4
Create Date: 2026-08-31 13:42:23.033522

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '65852ca7bb69'
down_revision: str | Sequence[str] | None = '659229e85be4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox_events',
    sa.Column('consumer_name', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('consumer_name', 'event_id')
    )
    op.create_table('rabbitmq_outbox_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_version', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('event_version > 0', name='ck_rabbitmq_outbox_events_event_version_positive'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_rabbitmq_outbox_events_unpublished_occurred_at', 'rabbitmq_outbox_events', ['occurred_at'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rabbitmq_outbox_events_unpublished_occurred_at', table_name='rabbitmq_outbox_events', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_table('rabbitmq_outbox_events')
    op.drop_table('inbox_events')
    # ### end Alembic commands ###
