"""add index ix_kafka_outbox_events_unpublished_aggregate_order to kafka_outbox_events

Revision ID: 2d0df90196c2
Revises: 55ce8321c1e2
Create Date: 2026-09-23 19:17:05.043120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d0df90196c2'
down_revision: Union[str, Sequence[str], None] = '55ce8321c1e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_kafka_outbox_events_unpublished_aggregate_order', 'kafka_outbox_events', ['aggregate_id', 'occurred_at', 'event_id'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_kafka_outbox_events_unpublished_aggregate_order', table_name='kafka_outbox_events', postgresql_where=sa.text('published_at IS NULL'))
    # ### end Alembic commands ###
