"""add_receipt_email_to_orders

Revision ID: 51d1cf100d72
Revises: ec140c0e972a
Create Date: 2026-07-27 14:49:05.213619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51d1cf100d72'
down_revision: Union[str, Sequence[str], None] = 'ec140c0e972a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('receipt_email', sa.String(length=320), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'receipt_email')
    # ### end Alembic commands ###
