"""add idempotency_key request_hash and uq constraint to orders table

Revision ID: 55ce8321c1e2
Revises: 6933749a76d0
Create Date: 2026-09-20 16:57:55.088745

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ce8321c1e2'
down_revision: Union[str, Sequence[str], None] = '6933749a76d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('idempotency_key', sa.String(length=128), nullable=True))
    op.add_column('orders', sa.Column('request_hash', sa.String(length=64), nullable=True))
    op.create_unique_constraint('uq_order_customer_id_idempotency_key', 'orders', ['customer_id', 'idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_order_customer_id_idempotency_key', 'orders', type_='unique')
    op.drop_column('orders', 'request_hash')
    op.drop_column('orders', 'idempotency_key')
    # ### end Alembic commands ###
