"""create payment tables

Revision ID: 2174cadb2270
Revises: 
Create Date: 2026-08-11 14:05:31.534685

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision: str = '2174cadb2270'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inbox_events',
    sa.Column('consumer_name', sa.String(length=100), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('consumer_name', 'event_id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('pending', 'succeeded', 'failed', name='payment_status'), server_default='pending', nullable=False),
    sa.Column('failure_code', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(status = 'pending' AND completed_at IS NULL AND failure_code IS NULL) OR (status = 'succeeded' AND completed_at IS NOT NULL AND failure_code IS NULL) OR (status = 'failed' AND completed_at IS NOT NULL AND failure_code IS NOT NULL)", name='ck_payments_status_fields_consistent'),
    sa.CheckConstraint("currency = 'RUB'", name='ck_payments_currency_rub'),
    sa.CheckConstraint('amount > 0', name='ck_payments_amount_positive'),
    sa.CheckConstraint('completed_at IS NULL OR completed_at >= created_at', name='ck_payments_completed_at_not_before_created_at'),
    sa.CheckConstraint('failure_code IS NULL OR length(btrim(failure_code)) > 0', name='ck_payments_failure_code_not_blank'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', name='uq_payments_order_id')
    )
    op.create_table('rabbitmq_outbox_events',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('aggregate_id', sa.Uuid(), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('event_version', sa.SmallInteger(), server_default='1', nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('event_version > 0', name='ck_rabbitmq_outbox_events_event_version_positive'),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index('ix_rabbitmq_outbox_events_unpublished_occurred_at', 'rabbitmq_outbox_events', ['occurred_at'], unique=False, postgresql_where=sa.text('published_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rabbitmq_outbox_events_unpublished_occurred_at', table_name='rabbitmq_outbox_events', postgresql_where=sa.text('published_at IS NULL'))
    op.drop_table('rabbitmq_outbox_events')
    op.drop_table('payments')
    op.drop_table('inbox_events')
    # ### end Alembic commands ###
