"""create analytics tables

Revision ID: 43bd58135533
Revises:
Create Date: 2026-08-03 14:12:22.348418

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "43bd58135533"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics_orders",
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("customer_id", sa.Uuid(), nullable=False),
        sa.Column("total_amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "total_amount >= 0", name="ck_analytics_orders_total_amount_non_negative"
        ),
        sa.PrimaryKeyConstraint("order_id"),
    )
    op.create_index(
        "ix_analytics_orders_created_at", "analytics_orders", ["created_at"], unique=False
    )
    op.create_index(
        "ix_analytics_orders_customer_created_at",
        "analytics_orders",
        ["customer_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "processed_events",
        sa.Column("consumer_name", sa.String(length=100), nullable=False),
        sa.Column("event_id", sa.Uuid(), nullable=False),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("consumer_name", "event_id"),
    )
    op.create_table(
        "analytics_order_items",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("order_id", sa.Uuid(), nullable=False),
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.CheckConstraint("quantity > 0", name="ck_analytics_order_items_quantity_positive"),
        sa.CheckConstraint(
            "unit_price >= 0", name="ck_analytics_order_items_unit_price_non_negative"
        ),
        sa.ForeignKeyConstraint(["order_id"], ["analytics_orders.order_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "order_id", "product_id", name="uq_analytics_order_items_order_product"
        ),
    )
    op.create_index(
        "ix_analytics_order_items_product_id", "analytics_order_items", ["product_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_analytics_order_items_product_id", table_name="analytics_order_items")
    op.drop_table("analytics_order_items")
    op.drop_table("processed_events")
    op.drop_index("ix_analytics_orders_customer_created_at", table_name="analytics_orders")
    op.drop_index("ix_analytics_orders_created_at", table_name="analytics_orders")
    op.drop_table("analytics_orders")
    # ### end Alembic commands ###
